COMMAND_ENABLE = no
AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
KEY_LOCK_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
DYNAMIC_MACRO_NO_NESTING = true
MOUSEKEY_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
RAW_ENABLE = yes
EEPROM_DRIVER = custom

USER_NAME := sprixes

DEBOUNCE_TYPE = asym_eager_defer_pk
