COMMAND_ENABLE = no
AUDIO_ENABLE = yes
BACKLIGHT_ENABLE = no
KEY_LOCK_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
DYNAMIC_MACRO_NO_NESTING = true
MOUSEKEY_ENABLE = yes
VIA_ENABLE = no

USER_NAME := sprixes
DEBOUNCE_TYPE = asym_eager_defer_pk
